# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: check-link-validity
on: 
    pull_request_target:
      types: [opened]

jobs:
  label:

    runs-on: windows-latest
    name: check link validity
    
    steps:
    - name: check validity
      uses: Chen-Zidi/check-modified-contents-link-validity-action@main
      id: check-validity
    - name: print validity result
      run: echo "validity - ${{ steps.check-validity.outputs.validity}}"


